[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[dependencies]
"@openzeppelin/contracts" = "5.0.0"

[rpc_endpoints]
0g_testnet = "https://evmrpc-testnet.0g.ai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
